name: beer
description: A Simple Web Framework
version: 0.1.0
repository: https://github.com/ethoDomingues/beer

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
